[2023-12-22T12:17:55.064+0000] {processor.py:156} INFO - Started process (PID=2228) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-22T12:17:55.065+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-22T12:17:55.070+0000] {logging_mixin.py:117} INFO - [2023-12-22T12:17:55.069+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-22T12:17:55.101+0000] {logging_mixin.py:117} INFO - [2023-12-22T12:17:55.097+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 6, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-22T12:17:55.102+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-22T12:17:55.156+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 0.103 seconds
[2023-12-22T12:18:25.374+0000] {processor.py:156} INFO - Started process (PID=2282) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-22T12:18:25.375+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-22T12:18:25.387+0000] {logging_mixin.py:117} INFO - [2023-12-22T12:18:25.383+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-22T12:18:25.404+0000] {logging_mixin.py:117} INFO - [2023-12-22T12:18:25.402+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 6, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-22T12:18:25.405+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-22T12:18:25.484+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 0.136 seconds
[2023-12-22T12:18:57.675+0000] {processor.py:156} INFO - Started process (PID=2338) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-22T12:18:57.708+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-22T12:18:57.720+0000] {logging_mixin.py:117} INFO - [2023-12-22T12:18:57.719+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-22T12:18:57.889+0000] {logging_mixin.py:117} INFO - [2023-12-22T12:18:57.871+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 6, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-22T12:18:57.890+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-22T12:18:58.118+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 0.505 seconds
[2023-12-22T12:19:28.548+0000] {processor.py:156} INFO - Started process (PID=2383) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-22T12:19:28.550+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-22T12:19:28.560+0000] {logging_mixin.py:117} INFO - [2023-12-22T12:19:28.559+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-22T12:19:28.597+0000] {logging_mixin.py:117} INFO - [2023-12-22T12:19:28.589+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 6, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-22T12:19:28.598+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-22T12:19:28.697+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 0.168 seconds
[2023-12-22T12:20:03.327+0000] {processor.py:156} INFO - Started process (PID=2435) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-22T12:20:03.330+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-22T12:20:03.331+0000] {logging_mixin.py:117} INFO - [2023-12-22T12:20:03.331+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-22T12:20:03.375+0000] {logging_mixin.py:117} INFO - [2023-12-22T12:20:03.365+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 6, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-22T12:20:03.376+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-22T12:20:03.563+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 0.267 seconds
[2023-12-22T12:20:36.344+0000] {processor.py:156} INFO - Started process (PID=2487) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-22T12:20:36.382+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-22T12:20:36.384+0000] {logging_mixin.py:117} INFO - [2023-12-22T12:20:36.383+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-22T12:20:36.400+0000] {logging_mixin.py:117} INFO - [2023-12-22T12:20:36.398+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 6, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-22T12:20:36.401+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-22T12:20:36.583+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 0.258 seconds
[2023-12-22T12:21:06.917+0000] {processor.py:156} INFO - Started process (PID=2539) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-22T12:21:06.918+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-22T12:21:06.920+0000] {logging_mixin.py:117} INFO - [2023-12-22T12:21:06.919+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-22T12:21:06.961+0000] {logging_mixin.py:117} INFO - [2023-12-22T12:21:06.959+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 6, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-22T12:21:06.962+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-22T12:21:07.084+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 0.189 seconds
[2023-12-22T12:21:37.273+0000] {processor.py:156} INFO - Started process (PID=2586) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-22T12:21:37.311+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-22T12:21:37.312+0000] {logging_mixin.py:117} INFO - [2023-12-22T12:21:37.312+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-22T12:21:37.325+0000] {logging_mixin.py:117} INFO - [2023-12-22T12:21:37.323+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 6, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-22T12:21:37.326+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-22T12:21:37.427+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 0.160 seconds
[2023-12-22T12:22:08.104+0000] {processor.py:156} INFO - Started process (PID=2642) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-22T12:22:08.138+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-22T12:22:08.140+0000] {logging_mixin.py:117} INFO - [2023-12-22T12:22:08.139+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-22T12:22:08.174+0000] {logging_mixin.py:117} INFO - [2023-12-22T12:22:08.172+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 6, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-22T12:22:08.175+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-22T12:22:08.419+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 0.340 seconds
[2023-12-22T12:22:39.825+0000] {processor.py:156} INFO - Started process (PID=2687) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-22T12:22:39.859+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-22T12:22:39.860+0000] {logging_mixin.py:117} INFO - [2023-12-22T12:22:39.860+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-22T12:22:39.928+0000] {logging_mixin.py:117} INFO - [2023-12-22T12:22:39.909+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 6, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-22T12:22:39.929+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-22T12:22:40.176+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 0.373 seconds
[2023-12-22T12:23:16.282+0000] {processor.py:156} INFO - Started process (PID=2749) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-22T12:23:16.327+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-22T12:23:16.329+0000] {logging_mixin.py:117} INFO - [2023-12-22T12:23:16.328+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-22T12:23:16.412+0000] {logging_mixin.py:117} INFO - [2023-12-22T12:23:16.375+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 6, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-22T12:23:16.417+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-22T12:23:16.849+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 0.649 seconds
[2023-12-22T12:23:47.746+0000] {processor.py:156} INFO - Started process (PID=2797) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-22T12:23:47.750+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-22T12:23:47.762+0000] {logging_mixin.py:117} INFO - [2023-12-22T12:23:47.761+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-22T12:23:47.850+0000] {logging_mixin.py:117} INFO - [2023-12-22T12:23:47.839+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 6, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-22T12:23:47.866+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-22T12:23:48.110+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 0.419 seconds
[2023-12-22T12:24:18.493+0000] {processor.py:156} INFO - Started process (PID=2852) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-22T12:24:18.526+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-22T12:24:18.527+0000] {logging_mixin.py:117} INFO - [2023-12-22T12:24:18.527+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-22T12:24:18.540+0000] {logging_mixin.py:117} INFO - [2023-12-22T12:24:18.538+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 6, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-22T12:24:18.541+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-22T12:24:18.644+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 0.159 seconds
[2023-12-22T12:24:49.651+0000] {processor.py:156} INFO - Started process (PID=2907) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-22T12:24:49.652+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-22T12:24:49.659+0000] {logging_mixin.py:117} INFO - [2023-12-22T12:24:49.653+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-22T12:24:49.695+0000] {logging_mixin.py:117} INFO - [2023-12-22T12:24:49.691+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 6, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-22T12:24:49.696+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-22T12:24:49.763+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 0.131 seconds
[2023-12-22T12:25:20.168+0000] {processor.py:156} INFO - Started process (PID=2953) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-22T12:25:20.202+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-22T12:25:20.203+0000] {logging_mixin.py:117} INFO - [2023-12-22T12:25:20.203+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-22T12:25:20.231+0000] {logging_mixin.py:117} INFO - [2023-12-22T12:25:20.229+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 6, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-22T12:25:20.232+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-22T12:25:20.362+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 0.210 seconds
[2023-12-22T12:25:50.859+0000] {processor.py:156} INFO - Started process (PID=3009) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-22T12:25:50.860+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-22T12:25:50.869+0000] {logging_mixin.py:117} INFO - [2023-12-22T12:25:50.861+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-22T12:25:50.906+0000] {logging_mixin.py:117} INFO - [2023-12-22T12:25:50.893+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 6, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-22T12:25:50.907+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-22T12:25:51.003+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 0.164 seconds
[2023-12-22T12:26:21.659+0000] {processor.py:156} INFO - Started process (PID=3066) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-22T12:26:21.694+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-22T12:26:21.695+0000] {logging_mixin.py:117} INFO - [2023-12-22T12:26:21.695+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-22T12:26:21.721+0000] {logging_mixin.py:117} INFO - [2023-12-22T12:26:21.719+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 6, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-22T12:26:21.722+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-22T12:26:21.834+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 0.199 seconds
[2023-12-22T12:26:52.352+0000] {processor.py:156} INFO - Started process (PID=3120) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-22T12:26:52.361+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-22T12:26:52.365+0000] {logging_mixin.py:117} INFO - [2023-12-22T12:26:52.364+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-22T12:26:52.396+0000] {logging_mixin.py:117} INFO - [2023-12-22T12:26:52.395+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 6, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-22T12:26:52.397+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-22T12:26:52.518+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 0.178 seconds
[2023-12-22T12:27:26.499+0000] {processor.py:156} INFO - Started process (PID=3166) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-22T12:27:26.536+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-22T12:27:26.541+0000] {logging_mixin.py:117} INFO - [2023-12-22T12:27:26.541+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-22T12:27:26.837+0000] {logging_mixin.py:117} INFO - [2023-12-22T12:27:26.798+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 6, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-22T12:27:26.877+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-22T12:27:27.646+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 1.220 seconds
[2023-12-22T12:29:52.941+0000] {processor.py:156} INFO - Started process (PID=3243) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-22T12:29:53.071+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-22T12:29:53.078+0000] {logging_mixin.py:117} INFO - [2023-12-22T12:29:53.078+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-22T12:29:53.405+0000] {logging_mixin.py:117} INFO - [2023-12-22T12:29:53.320+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 6, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-22T12:29:53.422+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-22T12:29:54.118+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 1.314 seconds
[2023-12-22T12:31:26.519+0000] {processor.py:156} INFO - Started process (PID=3310) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-22T12:31:26.538+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-22T12:31:26.540+0000] {logging_mixin.py:117} INFO - [2023-12-22T12:31:26.539+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-22T12:31:26.810+0000] {logging_mixin.py:117} INFO - [2023-12-22T12:31:26.758+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 6, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-22T12:31:26.812+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-22T12:31:29.399+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 2.889 seconds
[2023-12-22T12:33:03.105+0000] {processor.py:156} INFO - Started process (PID=3367) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-22T12:33:03.109+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-22T12:33:03.117+0000] {logging_mixin.py:117} INFO - [2023-12-22T12:33:03.116+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-22T12:33:03.170+0000] {logging_mixin.py:117} INFO - [2023-12-22T12:33:03.161+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 6, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-22T12:33:03.176+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-22T12:33:03.357+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 0.279 seconds
[2023-12-22T12:34:10.622+0000] {processor.py:156} INFO - Started process (PID=3416) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-22T12:34:10.686+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-22T12:34:10.688+0000] {logging_mixin.py:117} INFO - [2023-12-22T12:34:10.688+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-22T12:34:10.969+0000] {logging_mixin.py:117} INFO - [2023-12-22T12:34:10.933+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 6, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-22T12:34:10.970+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-22T12:34:11.849+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 1.467 seconds
[2023-12-22T12:35:08.589+0000] {processor.py:156} INFO - Started process (PID=3460) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-22T12:35:08.594+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-22T12:35:08.596+0000] {logging_mixin.py:117} INFO - [2023-12-22T12:35:08.595+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-22T12:35:08.636+0000] {logging_mixin.py:117} INFO - [2023-12-22T12:35:08.629+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 6, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-22T12:35:08.637+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-22T12:35:08.709+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 0.130 seconds
[2023-12-22T12:35:38.813+0000] {processor.py:156} INFO - Started process (PID=3514) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-22T12:35:38.815+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-22T12:35:38.816+0000] {logging_mixin.py:117} INFO - [2023-12-22T12:35:38.816+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-22T12:35:38.839+0000] {logging_mixin.py:117} INFO - [2023-12-22T12:35:38.833+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 6, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-22T12:35:38.840+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-22T12:35:39.001+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 0.202 seconds
[2023-12-22T12:36:15.206+0000] {processor.py:156} INFO - Started process (PID=3566) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-22T12:36:15.256+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-22T12:36:15.263+0000] {logging_mixin.py:117} INFO - [2023-12-22T12:36:15.263+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-22T12:36:15.362+0000] {logging_mixin.py:117} INFO - [2023-12-22T12:36:15.351+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 6, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-22T12:36:15.383+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-22T12:36:15.723+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 0.554 seconds
[2023-12-22T12:36:55.185+0000] {processor.py:156} INFO - Started process (PID=3599) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-22T12:36:55.205+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-22T12:36:55.208+0000] {logging_mixin.py:117} INFO - [2023-12-22T12:36:55.207+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-22T12:36:55.416+0000] {logging_mixin.py:117} INFO - [2023-12-22T12:36:55.398+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 6, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-22T12:36:55.421+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-22T12:36:56.246+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 1.170 seconds
[2023-12-22T12:38:24.068+0000] {processor.py:156} INFO - Started process (PID=3643) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-22T12:38:24.121+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-22T12:38:24.125+0000] {logging_mixin.py:117} INFO - [2023-12-22T12:38:24.124+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-22T12:38:24.705+0000] {logging_mixin.py:117} INFO - [2023-12-22T12:38:24.614+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 6, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-22T12:38:24.706+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-22T12:38:27.918+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 3.978 seconds
[2023-12-22T12:43:37.456+0000] {processor.py:156} INFO - Started process (PID=119) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-22T12:43:37.721+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-22T12:43:37.722+0000] {logging_mixin.py:117} INFO - [2023-12-22T12:43:37.722+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-22T12:43:38.346+0000] {logging_mixin.py:117} INFO - [2023-12-22T12:43:38.214+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 6, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-22T12:43:38.347+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-22T12:43:39.139+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 1.769 seconds
[2023-12-22T12:52:06.593+0000] {processor.py:156} INFO - Started process (PID=303) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-22T12:52:06.641+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-22T12:52:06.643+0000] {logging_mixin.py:117} INFO - [2023-12-22T12:52:06.643+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-22T12:52:06.797+0000] {logging_mixin.py:117} INFO - [2023-12-22T12:52:06.750+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 6, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-22T12:52:06.798+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-22T12:52:07.293+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 0.754 seconds
[2023-12-22T12:52:45.413+0000] {processor.py:156} INFO - Started process (PID=341) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-22T12:52:45.453+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-22T12:52:45.454+0000] {logging_mixin.py:117} INFO - [2023-12-22T12:52:45.454+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-22T12:52:45.482+0000] {logging_mixin.py:117} INFO - [2023-12-22T12:52:45.470+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 6, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-22T12:52:45.483+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-22T12:52:45.690+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 0.300 seconds
[2023-12-22T12:53:16.186+0000] {processor.py:156} INFO - Started process (PID=395) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-22T12:53:16.188+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-22T12:53:16.214+0000] {logging_mixin.py:117} INFO - [2023-12-22T12:53:16.214+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-22T12:53:16.322+0000] {logging_mixin.py:117} INFO - [2023-12-22T12:53:16.292+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 6, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-22T12:53:16.323+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-22T12:53:16.702+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 0.532 seconds
[2023-12-22T12:57:35.243+0000] {processor.py:156} INFO - Started process (PID=110) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-22T12:57:35.364+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-22T12:57:35.427+0000] {logging_mixin.py:117} INFO - [2023-12-22T12:57:35.426+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-22T12:57:36.284+0000] {logging_mixin.py:117} INFO - [2023-12-22T12:57:35.906+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 6, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-22T12:57:36.285+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-22T12:57:37.925+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 2.723 seconds
[2023-12-22T13:03:56.417+0000] {processor.py:156} INFO - Started process (PID=304) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-22T13:03:56.499+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-22T13:03:56.522+0000] {logging_mixin.py:117} INFO - [2023-12-22T13:03:56.522+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-22T13:03:56.873+0000] {logging_mixin.py:117} INFO - [2023-12-22T13:03:56.861+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 6, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-22T13:03:56.874+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-22T13:03:57.276+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 0.992 seconds
[2023-12-22T13:10:58.847+0000] {processor.py:156} INFO - Started process (PID=470) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-22T13:10:58.867+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-22T13:10:58.876+0000] {logging_mixin.py:117} INFO - [2023-12-22T13:10:58.875+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-22T13:11:00.154+0000] {logging_mixin.py:117} INFO - [2023-12-22T13:10:59.835+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 6, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-22T13:11:00.297+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-22T13:11:03.078+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 5.189 seconds
[2023-12-22T13:22:08.248+0000] {processor.py:156} INFO - Started process (PID=103) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-22T13:22:08.394+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-22T13:22:08.396+0000] {logging_mixin.py:117} INFO - [2023-12-22T13:22:08.395+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-22T13:22:08.871+0000] {logging_mixin.py:117} INFO - [2023-12-22T13:22:08.770+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 6, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-22T13:22:08.872+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-22T13:22:09.585+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 1.438 seconds
[2023-12-22T13:30:18.684+0000] {processor.py:156} INFO - Started process (PID=221) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-22T13:30:18.713+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-22T13:30:18.743+0000] {logging_mixin.py:117} INFO - [2023-12-22T13:30:18.743+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-22T13:30:19.141+0000] {logging_mixin.py:117} INFO - [2023-12-22T13:30:19.116+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 9, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-22T13:30:19.147+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-22T13:30:20.266+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 1.663 seconds
[2023-12-22T13:37:10.403+0000] {processor.py:156} INFO - Started process (PID=317) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-22T13:37:10.459+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-22T13:37:10.460+0000] {logging_mixin.py:117} INFO - [2023-12-22T13:37:10.460+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-22T13:37:10.961+0000] {logging_mixin.py:117} INFO - [2023-12-22T13:37:10.848+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 9, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-22T13:37:10.979+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-22T13:37:12.321+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 2.092 seconds
[2023-12-22T13:48:07.422+0000] {processor.py:156} INFO - Started process (PID=69) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-22T13:48:07.434+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-22T13:48:07.447+0000] {logging_mixin.py:117} INFO - [2023-12-22T13:48:07.435+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-22T13:48:07.584+0000] {logging_mixin.py:117} INFO - [2023-12-22T13:48:07.576+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 9, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-22T13:48:07.598+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-22T13:48:07.791+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 0.415 seconds
[2023-12-22T13:52:37.486+0000] {processor.py:156} INFO - Started process (PID=221) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-22T13:52:37.564+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-22T13:52:37.565+0000] {logging_mixin.py:117} INFO - [2023-12-22T13:52:37.565+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-22T13:52:39.420+0000] {logging_mixin.py:117} INFO - [2023-12-22T13:52:38.905+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 9, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-22T13:52:39.422+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-22T13:52:42.060+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 4.943 seconds
[2023-12-22T13:59:13.577+0000] {processor.py:156} INFO - Started process (PID=403) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-22T13:59:13.820+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-22T13:59:13.822+0000] {logging_mixin.py:117} INFO - [2023-12-22T13:59:13.821+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-22T13:59:15.074+0000] {logging_mixin.py:117} INFO - [2023-12-22T13:59:14.909+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 7, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-22T13:59:15.075+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-22T13:59:16.806+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 3.596 seconds
[2023-12-22T14:05:44.723+0000] {processor.py:156} INFO - Started process (PID=588) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-22T14:05:44.741+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-22T14:05:44.743+0000] {logging_mixin.py:117} INFO - [2023-12-22T14:05:44.742+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-22T14:05:44.959+0000] {logging_mixin.py:117} INFO - [2023-12-22T14:05:44.948+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 9, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-22T14:05:44.960+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-22T14:05:45.380+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 0.679 seconds
[2023-12-22T14:10:26.116+0000] {processor.py:156} INFO - Started process (PID=670) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-22T14:10:26.148+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-22T14:10:26.150+0000] {logging_mixin.py:117} INFO - [2023-12-22T14:10:26.150+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-22T14:10:26.376+0000] {logging_mixin.py:117} INFO - [2023-12-22T14:10:26.334+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 9, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-22T14:10:26.378+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-22T14:10:26.716+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 0.921 seconds
[2023-12-22T14:14:51.520+0000] {processor.py:156} INFO - Started process (PID=67) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-22T14:14:51.622+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-22T14:14:51.623+0000] {logging_mixin.py:117} INFO - [2023-12-22T14:14:51.623+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-22T14:14:52.182+0000] {logging_mixin.py:117} INFO - [2023-12-22T14:14:52.138+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 9, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-22T14:14:52.183+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-22T14:14:53.008+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 1.566 seconds
[2023-12-22T14:22:33.963+0000] {processor.py:156} INFO - Started process (PID=240) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-22T14:22:34.052+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-22T14:22:34.053+0000] {logging_mixin.py:117} INFO - [2023-12-22T14:22:34.053+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-22T14:22:34.700+0000] {logging_mixin.py:117} INFO - [2023-12-22T14:22:34.521+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 9, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-22T14:22:34.721+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-22T14:22:35.934+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 2.055 seconds
[2023-12-22T14:26:23.794+0000] {processor.py:156} INFO - Started process (PID=352) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-22T14:26:23.815+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-22T14:26:23.817+0000] {logging_mixin.py:117} INFO - [2023-12-22T14:26:23.816+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-22T14:26:24.601+0000] {logging_mixin.py:117} INFO - [2023-12-22T14:26:24.266+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 9, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-22T14:26:24.640+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-22T14:26:26.659+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 3.085 seconds
[2023-12-22T14:34:43.750+0000] {processor.py:156} INFO - Started process (PID=74) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-22T14:34:43.800+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-22T14:34:43.824+0000] {logging_mixin.py:117} INFO - [2023-12-22T14:34:43.818+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-22T14:34:44.204+0000] {logging_mixin.py:117} INFO - [2023-12-22T14:34:44.188+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 9, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-22T14:34:44.214+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-22T14:34:45.020+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 1.325 seconds
[2023-12-22T14:41:31.560+0000] {processor.py:156} INFO - Started process (PID=272) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-22T14:41:31.695+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-22T14:41:31.696+0000] {logging_mixin.py:117} INFO - [2023-12-22T14:41:31.696+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-22T14:41:32.791+0000] {logging_mixin.py:117} INFO - [2023-12-22T14:41:32.523+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 9, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-22T14:41:32.792+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-22T14:41:34.413+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 3.035 seconds
[2023-12-22T14:44:11.336+0000] {processor.py:156} INFO - Started process (PID=369) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-22T14:44:11.363+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-22T14:44:11.385+0000] {logging_mixin.py:117} INFO - [2023-12-22T14:44:11.364+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-22T14:44:11.598+0000] {logging_mixin.py:117} INFO - [2023-12-22T14:44:11.564+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 9, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-22T14:44:11.599+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-22T14:44:12.176+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 0.870 seconds
[2023-12-22T14:44:54.516+0000] {processor.py:156} INFO - Started process (PID=419) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-22T14:44:54.554+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-22T14:44:54.555+0000] {logging_mixin.py:117} INFO - [2023-12-22T14:44:54.555+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-22T14:44:54.714+0000] {logging_mixin.py:117} INFO - [2023-12-22T14:44:54.673+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 9, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-22T14:44:54.716+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-22T14:44:55.210+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 0.721 seconds
[2023-12-22T14:45:42.972+0000] {processor.py:156} INFO - Started process (PID=469) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-22T14:45:43.004+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-22T14:45:43.009+0000] {logging_mixin.py:117} INFO - [2023-12-22T14:45:43.008+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-22T14:45:43.281+0000] {logging_mixin.py:117} INFO - [2023-12-22T14:45:43.217+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 9, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-22T14:45:43.282+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-22T14:45:43.698+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 0.789 seconds
[2023-12-22T14:46:14.820+0000] {processor.py:156} INFO - Started process (PID=515) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-22T14:46:14.824+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-22T14:46:14.830+0000] {logging_mixin.py:117} INFO - [2023-12-22T14:46:14.830+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-22T14:46:14.866+0000] {logging_mixin.py:117} INFO - [2023-12-22T14:46:14.860+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 9, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-22T14:46:14.867+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-22T14:46:15.032+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 0.240 seconds
[2023-12-22T14:46:45.884+0000] {processor.py:156} INFO - Started process (PID=568) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-22T14:46:45.887+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-22T14:46:45.888+0000] {logging_mixin.py:117} INFO - [2023-12-22T14:46:45.888+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-22T14:46:45.908+0000] {logging_mixin.py:117} INFO - [2023-12-22T14:46:45.905+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 9, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-22T14:46:45.909+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-22T14:46:45.965+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 0.086 seconds
[2023-12-22T14:47:16.887+0000] {processor.py:156} INFO - Started process (PID=624) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-22T14:47:16.890+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-22T14:47:16.898+0000] {logging_mixin.py:117} INFO - [2023-12-22T14:47:16.895+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-22T14:47:16.932+0000] {logging_mixin.py:117} INFO - [2023-12-22T14:47:16.929+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 9, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-22T14:47:16.933+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-22T14:47:17.007+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 0.127 seconds
[2023-12-22T14:47:47.149+0000] {processor.py:156} INFO - Started process (PID=667) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-22T14:47:47.151+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-22T14:47:47.152+0000] {logging_mixin.py:117} INFO - [2023-12-22T14:47:47.152+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-22T14:47:47.170+0000] {logging_mixin.py:117} INFO - [2023-12-22T14:47:47.167+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 9, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-22T14:47:47.171+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-22T14:47:47.217+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 0.075 seconds
[2023-12-22T14:48:38.358+0000] {processor.py:156} INFO - Started process (PID=719) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-22T14:48:38.374+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-22T14:48:38.393+0000] {logging_mixin.py:117} INFO - [2023-12-22T14:48:38.386+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-22T14:48:38.688+0000] {logging_mixin.py:117} INFO - [2023-12-22T14:48:38.568+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 9, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-22T14:48:38.707+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-22T14:48:39.823+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 1.644 seconds
[2023-12-22T14:49:49.432+0000] {processor.py:156} INFO - Started process (PID=771) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-22T14:49:49.458+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-22T14:49:49.481+0000] {logging_mixin.py:117} INFO - [2023-12-22T14:49:49.459+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-22T14:49:49.640+0000] {logging_mixin.py:117} INFO - [2023-12-22T14:49:49.597+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 9, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-22T14:49:49.641+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-22T14:49:50.119+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 0.713 seconds
[2023-12-22T14:50:21.045+0000] {processor.py:156} INFO - Started process (PID=819) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-22T14:50:21.047+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-22T14:50:21.048+0000] {logging_mixin.py:117} INFO - [2023-12-22T14:50:21.048+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-22T14:50:21.081+0000] {logging_mixin.py:117} INFO - [2023-12-22T14:50:21.075+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 9, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-22T14:50:21.083+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-22T14:50:21.210+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 0.175 seconds
[2023-12-22T14:50:54.551+0000] {processor.py:156} INFO - Started process (PID=871) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-22T14:50:54.559+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-22T14:50:54.560+0000] {logging_mixin.py:117} INFO - [2023-12-22T14:50:54.560+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-22T14:50:54.630+0000] {logging_mixin.py:117} INFO - [2023-12-22T14:50:54.620+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 9, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-22T14:50:54.633+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-22T14:50:54.686+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 0.145 seconds
[2023-12-22T14:51:25.011+0000] {processor.py:156} INFO - Started process (PID=927) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-22T14:51:25.048+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-22T14:51:25.050+0000] {logging_mixin.py:117} INFO - [2023-12-22T14:51:25.050+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-22T14:51:25.072+0000] {logging_mixin.py:117} INFO - [2023-12-22T14:51:25.070+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 9, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-22T14:51:25.073+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-22T14:51:25.193+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 0.188 seconds
[2023-12-22T14:52:16.687+0000] {processor.py:156} INFO - Started process (PID=975) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-22T14:52:16.709+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-22T14:52:16.740+0000] {logging_mixin.py:117} INFO - [2023-12-22T14:52:16.740+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-22T14:52:18.343+0000] {logging_mixin.py:117} INFO - [2023-12-22T14:52:18.031+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 9, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-22T14:52:18.363+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-22T14:52:20.652+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 4.119 seconds
[2023-12-22T14:53:17.736+0000] {processor.py:156} INFO - Started process (PID=1030) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-22T14:53:17.749+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-22T14:53:17.787+0000] {logging_mixin.py:117} INFO - [2023-12-22T14:53:17.782+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-22T14:53:18.018+0000] {logging_mixin.py:117} INFO - [2023-12-22T14:53:18.013+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 9, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-22T14:53:18.019+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-22T14:53:18.256+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 0.597 seconds
[2023-12-22T14:54:05.702+0000] {processor.py:156} INFO - Started process (PID=1070) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-22T14:54:05.751+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-22T14:54:05.752+0000] {logging_mixin.py:117} INFO - [2023-12-22T14:54:05.752+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-22T14:54:05.919+0000] {logging_mixin.py:117} INFO - [2023-12-22T14:54:05.884+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 9, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-22T14:54:05.925+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-22T14:54:06.154+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 0.532 seconds
[2023-12-22T14:59:04.680+0000] {processor.py:156} INFO - Started process (PID=96) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-22T14:59:04.781+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-22T14:59:04.800+0000] {logging_mixin.py:117} INFO - [2023-12-22T14:59:04.799+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-22T14:59:05.654+0000] {logging_mixin.py:117} INFO - [2023-12-22T14:59:05.644+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 9, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-22T14:59:05.655+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-22T14:59:06.728+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 2.135 seconds
[2023-12-22T15:05:51.068+0000] {processor.py:156} INFO - Started process (PID=249) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-22T15:05:51.122+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-22T15:05:51.124+0000] {logging_mixin.py:117} INFO - [2023-12-22T15:05:51.123+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-22T15:05:51.640+0000] {logging_mixin.py:117} INFO - [2023-12-22T15:05:51.494+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 9, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-22T15:05:51.649+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-22T15:05:52.809+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 1.759 seconds
[2023-12-22T15:09:52.968+0000] {processor.py:156} INFO - Started process (PID=318) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-22T15:09:53.006+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-22T15:09:53.007+0000] {logging_mixin.py:117} INFO - [2023-12-22T15:09:53.007+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-22T15:09:53.301+0000] {logging_mixin.py:117} INFO - [2023-12-22T15:09:53.231+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 9, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-22T15:09:53.302+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-22T15:09:54.160+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 1.312 seconds
[2023-12-22T15:11:27.941+0000] {processor.py:156} INFO - Started process (PID=389) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-22T15:11:27.998+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-22T15:11:27.999+0000] {logging_mixin.py:117} INFO - [2023-12-22T15:11:27.999+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-22T15:11:28.106+0000] {logging_mixin.py:117} INFO - [2023-12-22T15:11:28.082+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 9, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-22T15:11:28.107+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-22T15:11:28.436+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 0.517 seconds
[2023-12-22T15:16:42.425+0000] {processor.py:156} INFO - Started process (PID=116) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-22T15:16:42.558+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-22T15:16:42.679+0000] {logging_mixin.py:117} INFO - [2023-12-22T15:16:42.626+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-22T15:16:43.569+0000] {logging_mixin.py:117} INFO - [2023-12-22T15:16:43.428+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 9, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-22T15:16:43.570+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-22T15:16:44.817+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 2.408 seconds
[2023-12-22T15:24:57.266+0000] {processor.py:156} INFO - Started process (PID=298) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-22T15:24:57.293+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-22T15:24:57.295+0000] {logging_mixin.py:117} INFO - [2023-12-22T15:24:57.295+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-22T15:24:57.738+0000] {logging_mixin.py:117} INFO - [2023-12-22T15:24:57.618+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 9, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-22T15:24:57.824+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-22T15:24:58.348+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 1.088 seconds
[2023-12-22T15:30:46.093+0000] {processor.py:156} INFO - Started process (PID=119) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-22T15:30:46.126+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-22T15:30:46.128+0000] {logging_mixin.py:117} INFO - [2023-12-22T15:30:46.127+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-22T15:30:46.311+0000] {logging_mixin.py:117} INFO - [2023-12-22T15:30:46.278+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 9, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-22T15:30:46.312+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-22T15:30:46.618+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 0.591 seconds
[2023-12-22T15:44:39.178+0000] {processor.py:156} INFO - Started process (PID=178) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-22T15:44:39.204+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-22T15:44:39.358+0000] {logging_mixin.py:117} INFO - [2023-12-22T15:44:39.357+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-22T15:44:40.454+0000] {logging_mixin.py:117} INFO - [2023-12-22T15:44:40.336+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 9, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-22T15:44:40.605+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-22T15:44:43.601+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 4.448 seconds
[2023-12-22T16:01:55.128+0000] {processor.py:156} INFO - Started process (PID=111) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-22T16:01:55.258+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-22T16:01:55.290+0000] {logging_mixin.py:117} INFO - [2023-12-22T16:01:55.289+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-22T16:01:55.654+0000] {logging_mixin.py:117} INFO - [2023-12-22T16:01:55.636+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 9, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-22T16:01:55.659+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-22T16:01:57.161+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 2.228 seconds
[2023-12-22T16:09:37.779+0000] {processor.py:156} INFO - Started process (PID=328) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-22T16:09:37.820+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-22T16:09:37.865+0000] {logging_mixin.py:117} INFO - [2023-12-22T16:09:37.865+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-22T16:09:38.484+0000] {logging_mixin.py:117} INFO - [2023-12-22T16:09:38.250+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 9, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-22T16:09:38.490+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-22T16:09:41.209+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 3.852 seconds
[2023-12-22T16:15:00.562+0000] {processor.py:156} INFO - Started process (PID=406) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-22T16:15:00.571+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-22T16:15:00.590+0000] {logging_mixin.py:117} INFO - [2023-12-22T16:15:00.590+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-22T16:15:01.389+0000] {logging_mixin.py:117} INFO - [2023-12-22T16:15:01.191+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 9, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-22T16:15:01.407+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-22T16:15:02.572+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 2.059 seconds
[2023-12-22T16:15:48.945+0000] {processor.py:156} INFO - Started process (PID=464) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-22T16:15:48.996+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-22T16:15:48.999+0000] {logging_mixin.py:117} INFO - [2023-12-22T16:15:48.999+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-22T16:15:49.196+0000] {logging_mixin.py:117} INFO - [2023-12-22T16:15:49.162+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 9, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-22T16:15:49.197+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-22T16:15:49.552+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 0.696 seconds
[2023-12-22T18:03:35.200+0000] {processor.py:156} INFO - Started process (PID=59) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-22T18:03:35.203+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-22T18:03:35.240+0000] {logging_mixin.py:117} INFO - [2023-12-22T18:03:35.240+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-22T18:03:35.681+0000] {logging_mixin.py:117} INFO - [2023-12-22T18:03:35.609+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 9, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-22T18:03:35.682+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-22T18:03:36.633+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 1.525 seconds
[2023-12-22T18:05:20.767+0000] {processor.py:156} INFO - Started process (PID=143) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-22T18:05:20.770+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-22T18:05:20.772+0000] {logging_mixin.py:117} INFO - [2023-12-22T18:05:20.771+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-22T18:05:20.803+0000] {logging_mixin.py:117} INFO - [2023-12-22T18:05:20.800+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 9, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-22T18:05:20.804+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-22T18:05:20.853+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 0.093 seconds
[2023-12-22T18:05:51.280+0000] {processor.py:156} INFO - Started process (PID=197) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-22T18:05:51.282+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-22T18:05:51.283+0000] {logging_mixin.py:117} INFO - [2023-12-22T18:05:51.283+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-22T18:05:51.299+0000] {logging_mixin.py:117} INFO - [2023-12-22T18:05:51.297+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 9, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-22T18:05:51.299+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-22T18:05:51.356+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 0.082 seconds
[2023-12-22T23:48:24.476+0000] {processor.py:156} INFO - Started process (PID=64) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-22T23:48:24.510+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-22T23:48:24.548+0000] {logging_mixin.py:117} INFO - [2023-12-22T23:48:24.511+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-22T23:48:24.798+0000] {logging_mixin.py:117} INFO - [2023-12-22T23:48:24.726+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 9, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-22T23:48:24.799+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-22T23:48:25.230+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 0.809 seconds
[2023-12-22T23:54:33.765+0000] {processor.py:156} INFO - Started process (PID=229) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-22T23:54:33.850+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-22T23:54:33.852+0000] {logging_mixin.py:117} INFO - [2023-12-22T23:54:33.851+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-22T23:54:34.687+0000] {logging_mixin.py:117} INFO - [2023-12-22T23:54:34.579+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 9, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-22T23:54:34.688+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-22T23:54:36.367+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 2.819 seconds
