[2023-12-23T00:00:35.934+0000] {processor.py:156} INFO - Started process (PID=284) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-23T00:00:35.963+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-23T00:00:36.126+0000] {logging_mixin.py:117} INFO - [2023-12-23T00:00:36.126+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-23T00:00:36.682+0000] {logging_mixin.py:117} INFO - [2023-12-23T00:00:36.669+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 9, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-23T00:00:36.692+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-23T00:00:36.845+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 1.332 seconds
[2023-12-23T00:01:49.284+0000] {processor.py:156} INFO - Started process (PID=348) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-23T00:01:49.370+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-23T00:01:49.371+0000] {logging_mixin.py:117} INFO - [2023-12-23T00:01:49.371+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-23T00:01:49.750+0000] {logging_mixin.py:117} INFO - [2023-12-23T00:01:49.633+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 9, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-23T00:01:49.751+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-23T00:01:50.398+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 1.183 seconds
[2023-12-23T00:03:02.133+0000] {processor.py:156} INFO - Started process (PID=389) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-23T00:03:02.291+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-23T00:03:02.292+0000] {logging_mixin.py:117} INFO - [2023-12-23T00:03:02.292+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-23T00:03:03.041+0000] {logging_mixin.py:117} INFO - [2023-12-23T00:03:02.977+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 9, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-23T00:03:03.042+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-23T00:03:05.223+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 3.664 seconds
[2023-12-23T00:07:26.854+0000] {processor.py:156} INFO - Started process (PID=480) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-23T00:07:26.906+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-23T00:07:26.959+0000] {logging_mixin.py:117} INFO - [2023-12-23T00:07:26.959+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-23T00:07:27.587+0000] {logging_mixin.py:117} INFO - [2023-12-23T00:07:27.502+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 9, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-23T00:07:27.607+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-23T00:07:28.901+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 2.302 seconds
[2023-12-23T00:10:33.115+0000] {processor.py:156} INFO - Started process (PID=82) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-23T00:10:33.153+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-23T00:10:33.213+0000] {logging_mixin.py:117} INFO - [2023-12-23T00:10:33.212+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-23T00:10:33.982+0000] {logging_mixin.py:117} INFO - [2023-12-23T00:10:33.848+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 9, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-23T00:10:33.983+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-23T00:10:34.837+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 1.928 seconds
[2023-12-23T00:17:27.901+0000] {processor.py:156} INFO - Started process (PID=257) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-23T00:17:27.968+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-23T00:17:28.195+0000] {logging_mixin.py:117} INFO - [2023-12-23T00:17:28.194+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-23T00:17:29.637+0000] {logging_mixin.py:117} INFO - [2023-12-23T00:17:29.315+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 9, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-23T00:17:29.638+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-23T00:17:31.460+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 3.797 seconds
[2023-12-23T00:25:21.121+0000] {processor.py:156} INFO - Started process (PID=365) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-23T00:25:21.203+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-23T00:25:21.246+0000] {logging_mixin.py:117} INFO - [2023-12-23T00:25:21.204+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-23T00:25:22.078+0000] {logging_mixin.py:117} INFO - [2023-12-23T00:25:21.846+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 9, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-23T00:25:22.079+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-23T00:25:24.084+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 3.180 seconds
[2023-12-23T00:26:32.615+0000] {processor.py:156} INFO - Started process (PID=422) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-23T00:26:32.717+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-23T00:26:32.719+0000] {logging_mixin.py:117} INFO - [2023-12-23T00:26:32.718+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-23T00:26:33.073+0000] {logging_mixin.py:117} INFO - [2023-12-23T00:26:33.030+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 9, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-23T00:26:33.084+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-23T00:26:34.069+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 1.569 seconds
[2023-12-23T00:27:30.677+0000] {processor.py:156} INFO - Started process (PID=465) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-23T00:27:30.689+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-23T00:27:30.691+0000] {logging_mixin.py:117} INFO - [2023-12-23T00:27:30.690+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-23T00:27:31.497+0000] {logging_mixin.py:117} INFO - [2023-12-23T00:27:31.387+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 9, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-23T00:27:31.501+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-23T00:27:32.997+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 2.527 seconds
[2023-12-23T00:30:45.115+0000] {processor.py:156} INFO - Started process (PID=546) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-23T00:30:45.195+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-23T00:30:45.311+0000] {logging_mixin.py:117} INFO - [2023-12-23T00:30:45.310+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-23T00:30:46.170+0000] {logging_mixin.py:117} INFO - [2023-12-23T00:30:46.115+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 9, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-23T00:30:46.172+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-23T00:30:48.070+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 3.147 seconds
[2023-12-23T00:38:07.858+0000] {processor.py:156} INFO - Started process (PID=667) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-23T00:38:07.999+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-23T00:38:08.090+0000] {logging_mixin.py:117} INFO - [2023-12-23T00:38:08.079+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-23T00:38:08.994+0000] {logging_mixin.py:117} INFO - [2023-12-23T00:38:08.839+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 9, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-23T00:38:09.097+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-23T00:38:11.576+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 4.289 seconds
[2023-12-23T00:42:03.519+0000] {processor.py:156} INFO - Started process (PID=772) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-23T00:42:03.548+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-23T00:42:03.549+0000] {logging_mixin.py:117} INFO - [2023-12-23T00:42:03.549+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-23T00:42:03.655+0000] {logging_mixin.py:117} INFO - [2023-12-23T00:42:03.646+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 9, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-23T00:42:03.656+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-23T00:42:03.838+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 0.329 seconds
[2023-12-23T00:43:07.694+0000] {processor.py:156} INFO - Started process (PID=831) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-23T00:43:08.004+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-23T00:43:08.006+0000] {logging_mixin.py:117} INFO - [2023-12-23T00:43:08.006+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-23T00:43:08.553+0000] {logging_mixin.py:117} INFO - [2023-12-23T00:43:08.470+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 9, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-23T00:43:08.581+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-23T00:43:09.820+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 2.375 seconds
[2023-12-23T00:43:43.892+0000] {processor.py:156} INFO - Started process (PID=878) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-23T00:43:43.936+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-23T00:43:43.937+0000] {logging_mixin.py:117} INFO - [2023-12-23T00:43:43.937+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-23T00:43:43.955+0000] {logging_mixin.py:117} INFO - [2023-12-23T00:43:43.953+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 9, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-23T00:43:43.956+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-23T00:43:44.010+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 0.124 seconds
[2023-12-23T00:44:14.310+0000] {processor.py:156} INFO - Started process (PID=933) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-23T00:44:14.311+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-23T00:44:14.313+0000] {logging_mixin.py:117} INFO - [2023-12-23T00:44:14.312+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-23T00:44:14.327+0000] {logging_mixin.py:117} INFO - [2023-12-23T00:44:14.325+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 9, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-23T00:44:14.331+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-23T00:44:14.416+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 0.112 seconds
[2023-12-23T00:44:44.514+0000] {processor.py:156} INFO - Started process (PID=987) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-23T00:44:44.560+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-23T00:44:44.561+0000] {logging_mixin.py:117} INFO - [2023-12-23T00:44:44.561+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-23T00:44:44.576+0000] {logging_mixin.py:117} INFO - [2023-12-23T00:44:44.574+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 9, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-23T00:44:44.577+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-23T00:44:44.716+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 0.208 seconds
[2023-12-23T00:45:14.835+0000] {processor.py:156} INFO - Started process (PID=1041) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-23T00:45:14.837+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-23T00:45:14.838+0000] {logging_mixin.py:117} INFO - [2023-12-23T00:45:14.838+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-23T00:45:14.930+0000] {logging_mixin.py:117} INFO - [2023-12-23T00:45:14.903+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 9, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-23T00:45:14.931+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-23T00:45:15.051+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 0.239 seconds
[2023-12-23T00:45:45.544+0000] {processor.py:156} INFO - Started process (PID=1105) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-23T00:45:45.580+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-23T00:45:45.581+0000] {logging_mixin.py:117} INFO - [2023-12-23T00:45:45.581+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-23T00:45:45.611+0000] {logging_mixin.py:117} INFO - [2023-12-23T00:45:45.609+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 9, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-23T00:45:45.612+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-23T00:45:45.728+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 0.202 seconds
[2023-12-23T00:46:16.279+0000] {processor.py:156} INFO - Started process (PID=1157) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-23T00:46:16.280+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-23T00:46:16.282+0000] {logging_mixin.py:117} INFO - [2023-12-23T00:46:16.281+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-23T00:46:16.296+0000] {logging_mixin.py:117} INFO - [2023-12-23T00:46:16.294+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 9, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-23T00:46:16.297+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-23T00:46:16.388+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 0.116 seconds
[2023-12-23T00:46:46.584+0000] {processor.py:156} INFO - Started process (PID=1211) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-23T00:46:46.628+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-23T00:46:46.630+0000] {logging_mixin.py:117} INFO - [2023-12-23T00:46:46.629+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-23T00:46:46.647+0000] {logging_mixin.py:117} INFO - [2023-12-23T00:46:46.645+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 9, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-23T00:46:46.648+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-23T00:46:46.788+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 0.222 seconds
[2023-12-23T00:47:17.052+0000] {processor.py:156} INFO - Started process (PID=1265) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-23T00:47:17.054+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-23T00:47:17.055+0000] {logging_mixin.py:117} INFO - [2023-12-23T00:47:17.055+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-23T00:47:17.069+0000] {logging_mixin.py:117} INFO - [2023-12-23T00:47:17.067+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 9, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-23T00:47:17.070+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-23T00:47:17.129+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 0.083 seconds
[2023-12-23T00:47:47.510+0000] {processor.py:156} INFO - Started process (PID=1320) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-23T00:47:47.530+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-23T00:47:47.532+0000] {logging_mixin.py:117} INFO - [2023-12-23T00:47:47.531+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-23T00:47:47.548+0000] {logging_mixin.py:117} INFO - [2023-12-23T00:47:47.546+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 9, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-23T00:47:47.549+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-23T00:47:47.668+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 0.164 seconds
[2023-12-23T00:48:17.992+0000] {processor.py:156} INFO - Started process (PID=1373) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-23T00:48:17.994+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-23T00:48:17.995+0000] {logging_mixin.py:117} INFO - [2023-12-23T00:48:17.995+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-23T00:48:18.017+0000] {logging_mixin.py:117} INFO - [2023-12-23T00:48:18.014+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 9, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-23T00:48:18.018+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-23T00:48:18.065+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 0.092 seconds
[2023-12-23T00:48:48.350+0000] {processor.py:156} INFO - Started process (PID=1428) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-23T00:48:48.359+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-23T00:48:48.361+0000] {logging_mixin.py:117} INFO - [2023-12-23T00:48:48.360+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-23T00:48:48.422+0000] {logging_mixin.py:117} INFO - [2023-12-23T00:48:48.417+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 9, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-23T00:48:48.425+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-23T00:48:48.536+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 0.219 seconds
[2023-12-23T00:49:18.827+0000] {processor.py:156} INFO - Started process (PID=1481) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-23T00:49:18.829+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-23T00:49:18.830+0000] {logging_mixin.py:117} INFO - [2023-12-23T00:49:18.830+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-23T00:49:18.844+0000] {logging_mixin.py:117} INFO - [2023-12-23T00:49:18.842+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 9, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-23T00:49:18.845+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-23T00:49:18.891+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 0.070 seconds
[2023-12-23T00:49:49.370+0000] {processor.py:156} INFO - Started process (PID=1534) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-23T00:49:49.412+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-23T00:49:49.413+0000] {logging_mixin.py:117} INFO - [2023-12-23T00:49:49.413+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-23T00:49:49.428+0000] {logging_mixin.py:117} INFO - [2023-12-23T00:49:49.426+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 9, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-23T00:49:49.429+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-23T00:49:49.532+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 0.170 seconds
[2023-12-23T00:50:19.641+0000] {processor.py:156} INFO - Started process (PID=1586) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-23T00:50:19.642+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-23T00:50:19.643+0000] {logging_mixin.py:117} INFO - [2023-12-23T00:50:19.643+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-23T00:50:19.678+0000] {logging_mixin.py:117} INFO - [2023-12-23T00:50:19.668+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 9, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-23T00:50:19.679+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-23T00:50:19.824+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 0.196 seconds
[2023-12-23T00:50:50.030+0000] {processor.py:156} INFO - Started process (PID=1638) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-23T00:50:50.067+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-23T00:50:50.073+0000] {logging_mixin.py:117} INFO - [2023-12-23T00:50:50.072+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-23T00:50:50.099+0000] {logging_mixin.py:117} INFO - [2023-12-23T00:50:50.097+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 9, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-23T00:50:50.100+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-23T00:50:50.256+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 0.241 seconds
[2023-12-23T00:51:20.562+0000] {processor.py:156} INFO - Started process (PID=1700) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-23T00:51:20.563+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-23T00:51:20.573+0000] {logging_mixin.py:117} INFO - [2023-12-23T00:51:20.573+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-23T00:51:20.604+0000] {logging_mixin.py:117} INFO - [2023-12-23T00:51:20.602+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 9, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-23T00:51:20.613+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-23T00:51:20.765+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 0.215 seconds
[2023-12-23T00:51:50.917+0000] {processor.py:156} INFO - Started process (PID=1757) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-23T00:51:50.968+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-23T00:51:50.969+0000] {logging_mixin.py:117} INFO - [2023-12-23T00:51:50.969+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-23T00:51:50.984+0000] {logging_mixin.py:117} INFO - [2023-12-23T00:51:50.982+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 9, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-23T00:51:50.985+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-23T00:51:51.030+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 0.119 seconds
[2023-12-23T00:52:21.326+0000] {processor.py:156} INFO - Started process (PID=1811) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-23T00:52:21.375+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-23T00:52:21.377+0000] {logging_mixin.py:117} INFO - [2023-12-23T00:52:21.377+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-23T00:52:21.391+0000] {logging_mixin.py:117} INFO - [2023-12-23T00:52:21.389+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 9, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-23T00:52:21.392+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-23T00:52:21.446+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 0.126 seconds
[2023-12-23T00:52:52.169+0000] {processor.py:156} INFO - Started process (PID=1865) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-23T00:52:52.208+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-23T00:52:52.210+0000] {logging_mixin.py:117} INFO - [2023-12-23T00:52:52.209+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-23T00:52:52.245+0000] {logging_mixin.py:117} INFO - [2023-12-23T00:52:52.243+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 9, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-23T00:52:52.246+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-23T00:52:52.292+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 0.136 seconds
[2023-12-23T00:53:22.923+0000] {processor.py:156} INFO - Started process (PID=1921) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-23T00:53:22.929+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-23T00:53:22.931+0000] {logging_mixin.py:117} INFO - [2023-12-23T00:53:22.930+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-23T00:53:22.963+0000] {logging_mixin.py:117} INFO - [2023-12-23T00:53:22.958+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 9, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-23T00:53:22.976+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-23T00:53:23.122+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 0.252 seconds
[2023-12-23T00:53:54.037+0000] {processor.py:156} INFO - Started process (PID=1976) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-23T00:53:54.039+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-23T00:53:54.040+0000] {logging_mixin.py:117} INFO - [2023-12-23T00:53:54.040+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-23T00:53:54.066+0000] {logging_mixin.py:117} INFO - [2023-12-23T00:53:54.064+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 9, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-23T00:53:54.066+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-23T00:53:54.117+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 0.091 seconds
[2023-12-23T00:54:24.688+0000] {processor.py:156} INFO - Started process (PID=2030) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-23T00:54:24.735+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-23T00:54:24.737+0000] {logging_mixin.py:117} INFO - [2023-12-23T00:54:24.737+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-23T00:54:24.761+0000] {logging_mixin.py:117} INFO - [2023-12-23T00:54:24.755+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 9, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-23T00:54:24.762+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-23T00:54:24.824+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 0.146 seconds
[2023-12-23T00:54:55.770+0000] {processor.py:156} INFO - Started process (PID=2085) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-23T00:54:55.771+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-23T00:54:55.773+0000] {logging_mixin.py:117} INFO - [2023-12-23T00:54:55.773+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-23T00:54:55.789+0000] {logging_mixin.py:117} INFO - [2023-12-23T00:54:55.787+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 9, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-23T00:54:55.790+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-23T00:54:55.837+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 0.073 seconds
[2023-12-23T00:55:26.535+0000] {processor.py:156} INFO - Started process (PID=2140) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-23T00:55:26.553+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-23T00:55:26.554+0000] {logging_mixin.py:117} INFO - [2023-12-23T00:55:26.554+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-23T00:55:26.674+0000] {logging_mixin.py:117} INFO - [2023-12-23T00:55:26.673+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 9, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-23T00:55:26.675+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-23T00:55:26.855+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 0.338 seconds
[2023-12-23T00:55:56.942+0000] {processor.py:156} INFO - Started process (PID=2195) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-23T00:55:56.944+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-23T00:55:56.945+0000] {logging_mixin.py:117} INFO - [2023-12-23T00:55:56.945+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-23T00:55:56.973+0000] {logging_mixin.py:117} INFO - [2023-12-23T00:55:56.957+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 9, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-23T00:55:56.974+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-23T00:55:57.092+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 0.156 seconds
[2023-12-23T00:56:27.512+0000] {processor.py:156} INFO - Started process (PID=2250) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-23T00:56:27.560+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-23T00:56:27.561+0000] {logging_mixin.py:117} INFO - [2023-12-23T00:56:27.561+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-23T00:56:27.609+0000] {logging_mixin.py:117} INFO - [2023-12-23T00:56:27.602+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 9, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-23T00:56:27.610+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-23T00:56:27.656+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 0.152 seconds
[2023-12-23T00:56:57.788+0000] {processor.py:156} INFO - Started process (PID=2303) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-23T00:56:57.789+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-23T00:56:57.790+0000] {logging_mixin.py:117} INFO - [2023-12-23T00:56:57.790+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-23T00:56:57.807+0000] {logging_mixin.py:117} INFO - [2023-12-23T00:56:57.805+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 9, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-23T00:56:57.808+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-23T00:56:57.855+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 0.073 seconds
[2023-12-23T00:57:28.127+0000] {processor.py:156} INFO - Started process (PID=2358) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-23T00:57:28.164+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-23T00:57:28.165+0000] {logging_mixin.py:117} INFO - [2023-12-23T00:57:28.165+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-23T00:57:28.181+0000] {logging_mixin.py:117} INFO - [2023-12-23T00:57:28.178+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 9, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-23T00:57:28.182+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-23T00:57:28.227+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 0.106 seconds
[2023-12-23T00:57:59.686+0000] {processor.py:156} INFO - Started process (PID=2413) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-23T00:57:59.687+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-23T00:57:59.689+0000] {logging_mixin.py:117} INFO - [2023-12-23T00:57:59.688+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-23T00:57:59.702+0000] {logging_mixin.py:117} INFO - [2023-12-23T00:57:59.700+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 9, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-23T00:57:59.703+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-23T00:57:59.828+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 0.150 seconds
[2023-12-23T00:58:29.967+0000] {processor.py:156} INFO - Started process (PID=2465) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-23T00:58:30.000+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-23T00:58:30.004+0000] {logging_mixin.py:117} INFO - [2023-12-23T00:58:30.004+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-23T00:58:30.032+0000] {logging_mixin.py:117} INFO - [2023-12-23T00:58:30.030+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 9, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-23T00:58:30.045+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-23T00:58:30.173+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 0.223 seconds
[2023-12-23T00:59:00.533+0000] {processor.py:156} INFO - Started process (PID=2510) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-23T00:59:00.580+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-23T00:59:00.581+0000] {logging_mixin.py:117} INFO - [2023-12-23T00:59:00.581+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-23T00:59:00.595+0000] {logging_mixin.py:117} INFO - [2023-12-23T00:59:00.592+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 9, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-23T00:59:00.596+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-23T00:59:00.643+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 0.117 seconds
[2023-12-23T00:59:36.708+0000] {processor.py:156} INFO - Started process (PID=2563) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-23T00:59:36.733+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-23T00:59:36.734+0000] {logging_mixin.py:117} INFO - [2023-12-23T00:59:36.734+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-23T00:59:36.938+0000] {logging_mixin.py:117} INFO - [2023-12-23T00:59:36.898+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 9, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-23T00:59:36.939+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-23T00:59:37.482+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 0.806 seconds
[2023-12-23T01:06:07.126+0000] {processor.py:156} INFO - Started process (PID=82) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:06:07.170+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-23T01:06:07.172+0000] {logging_mixin.py:117} INFO - [2023-12-23T01:06:07.171+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:06:07.494+0000] {logging_mixin.py:117} INFO - [2023-12-23T01:06:07.434+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 9, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-23T01:06:07.495+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:06:07.932+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 0.861 seconds
[2023-12-23T01:08:16.031+0000] {processor.py:156} INFO - Started process (PID=175) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:08:16.065+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-23T01:08:16.067+0000] {logging_mixin.py:117} INFO - [2023-12-23T01:08:16.066+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:08:17.641+0000] {logging_mixin.py:117} INFO - [2023-12-23T01:08:17.634+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 9, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-23T01:08:17.642+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:08:17.785+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 1.788 seconds
[2023-12-23T01:09:00.711+0000] {processor.py:156} INFO - Started process (PID=218) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:09:00.721+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-23T01:09:00.723+0000] {logging_mixin.py:117} INFO - [2023-12-23T01:09:00.722+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:09:00.757+0000] {logging_mixin.py:117} INFO - [2023-12-23T01:09:00.753+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 9, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-23T01:09:00.759+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:09:00.854+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 0.172 seconds
[2023-12-23T01:09:37.536+0000] {processor.py:156} INFO - Started process (PID=271) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:09:37.539+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-23T01:09:37.541+0000] {logging_mixin.py:117} INFO - [2023-12-23T01:09:37.540+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:09:37.560+0000] {logging_mixin.py:117} INFO - [2023-12-23T01:09:37.557+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 9, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-23T01:09:37.561+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:09:37.607+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 0.081 seconds
[2023-12-23T01:10:08.289+0000] {processor.py:156} INFO - Started process (PID=322) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:10:08.292+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-23T01:10:08.294+0000] {logging_mixin.py:117} INFO - [2023-12-23T01:10:08.294+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:10:08.392+0000] {logging_mixin.py:117} INFO - [2023-12-23T01:10:08.383+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 9, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-23T01:10:08.410+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:10:08.723+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 0.464 seconds
[2023-12-23T01:10:38.993+0000] {processor.py:156} INFO - Started process (PID=368) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:10:39.033+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-23T01:10:39.034+0000] {logging_mixin.py:117} INFO - [2023-12-23T01:10:39.034+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:10:39.049+0000] {logging_mixin.py:117} INFO - [2023-12-23T01:10:39.046+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 9, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-23T01:10:39.050+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:10:39.102+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 0.116 seconds
[2023-12-23T01:11:10.775+0000] {processor.py:156} INFO - Started process (PID=422) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:11:10.811+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-23T01:11:10.816+0000] {logging_mixin.py:117} INFO - [2023-12-23T01:11:10.816+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:11:10.846+0000] {logging_mixin.py:117} INFO - [2023-12-23T01:11:10.843+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 9, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-23T01:11:10.847+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:11:10.961+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 0.212 seconds
[2023-12-23T01:11:44.752+0000] {processor.py:156} INFO - Started process (PID=477) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:11:44.775+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-23T01:11:44.794+0000] {logging_mixin.py:117} INFO - [2023-12-23T01:11:44.776+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:11:44.927+0000] {logging_mixin.py:117} INFO - [2023-12-23T01:11:44.924+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 9, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-23T01:11:44.928+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:11:45.353+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 0.623 seconds
[2023-12-23T01:12:41.427+0000] {processor.py:156} INFO - Started process (PID=537) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:12:41.475+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-23T01:12:41.495+0000] {logging_mixin.py:117} INFO - [2023-12-23T01:12:41.495+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:12:41.673+0000] {logging_mixin.py:117} INFO - [2023-12-23T01:12:41.670+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 9, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-23T01:12:41.674+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:12:41.880+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 0.468 seconds
[2023-12-23T01:13:33.560+0000] {processor.py:156} INFO - Started process (PID=586) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:13:33.657+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-23T01:13:33.659+0000] {logging_mixin.py:117} INFO - [2023-12-23T01:13:33.659+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:13:33.981+0000] {logging_mixin.py:117} INFO - [2023-12-23T01:13:33.939+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 9, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-23T01:13:33.982+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:13:34.489+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 1.018 seconds
[2023-12-23T01:14:18.246+0000] {processor.py:156} INFO - Started process (PID=638) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:14:18.260+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-23T01:14:18.267+0000] {logging_mixin.py:117} INFO - [2023-12-23T01:14:18.266+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:14:18.523+0000] {logging_mixin.py:117} INFO - [2023-12-23T01:14:18.507+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 9, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-23T01:14:18.538+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:14:18.931+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 0.710 seconds
[2023-12-23T01:15:01.633+0000] {processor.py:156} INFO - Started process (PID=675) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:15:01.664+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-23T01:15:01.743+0000] {logging_mixin.py:117} INFO - [2023-12-23T01:15:01.708+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:15:02.194+0000] {logging_mixin.py:117} INFO - [2023-12-23T01:15:02.166+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 9, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-23T01:15:02.212+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:15:02.488+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 1.139 seconds
[2023-12-23T01:15:59.155+0000] {processor.py:156} INFO - Started process (PID=725) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:15:59.183+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-23T01:15:59.214+0000] {logging_mixin.py:117} INFO - [2023-12-23T01:15:59.208+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:15:59.313+0000] {logging_mixin.py:117} INFO - [2023-12-23T01:15:59.306+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 9, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-23T01:15:59.314+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:15:59.377+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 0.268 seconds
[2023-12-23T01:16:31.574+0000] {processor.py:156} INFO - Started process (PID=775) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:16:31.579+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-23T01:16:31.580+0000] {logging_mixin.py:117} INFO - [2023-12-23T01:16:31.580+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:16:31.636+0000] {logging_mixin.py:117} INFO - [2023-12-23T01:16:31.634+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 9, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-23T01:16:31.653+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:16:31.847+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 0.292 seconds
[2023-12-23T01:17:05.662+0000] {processor.py:156} INFO - Started process (PID=823) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:17:05.698+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-23T01:17:05.714+0000] {logging_mixin.py:117} INFO - [2023-12-23T01:17:05.713+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:17:06.042+0000] {logging_mixin.py:117} INFO - [2023-12-23T01:17:06.006+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 9, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-23T01:17:06.043+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:17:06.749+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 1.195 seconds
[2023-12-23T01:21:05.218+0000] {processor.py:156} INFO - Started process (PID=910) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:21:05.321+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-23T01:21:05.323+0000] {logging_mixin.py:117} INFO - [2023-12-23T01:21:05.322+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:21:05.595+0000] {logging_mixin.py:117} INFO - [2023-12-23T01:21:05.545+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 9, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-23T01:21:05.624+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:21:06.037+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 0.904 seconds
[2023-12-23T01:21:36.841+0000] {processor.py:156} INFO - Started process (PID=958) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:21:36.843+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-23T01:21:36.844+0000] {logging_mixin.py:117} INFO - [2023-12-23T01:21:36.844+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:21:36.873+0000] {logging_mixin.py:117} INFO - [2023-12-23T01:21:36.872+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 9, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-23T01:21:36.874+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:21:37.153+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 0.336 seconds
[2023-12-23T01:22:07.609+0000] {processor.py:156} INFO - Started process (PID=1013) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:22:07.644+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-23T01:22:07.645+0000] {logging_mixin.py:117} INFO - [2023-12-23T01:22:07.645+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:22:07.667+0000] {logging_mixin.py:117} INFO - [2023-12-23T01:22:07.665+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 9, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-23T01:22:07.668+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:22:07.809+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 0.217 seconds
[2023-12-23T01:22:38.261+0000] {processor.py:156} INFO - Started process (PID=1067) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:22:38.263+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-23T01:22:38.264+0000] {logging_mixin.py:117} INFO - [2023-12-23T01:22:38.264+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:22:38.391+0000] {logging_mixin.py:117} INFO - [2023-12-23T01:22:38.331+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 9, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-23T01:22:38.392+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:22:38.534+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 0.304 seconds
[2023-12-23T01:24:55.566+0000] {processor.py:156} INFO - Started process (PID=1138) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:24:55.600+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-23T01:24:55.602+0000] {logging_mixin.py:117} INFO - [2023-12-23T01:24:55.601+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:24:56.241+0000] {logging_mixin.py:117} INFO - [2023-12-23T01:24:56.165+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 9, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-23T01:24:56.242+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:24:57.135+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 1.587 seconds
[2023-12-23T01:29:09.627+0000] {processor.py:156} INFO - Started process (PID=1204) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:29:09.666+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-23T01:29:09.668+0000] {logging_mixin.py:117} INFO - [2023-12-23T01:29:09.668+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:29:09.789+0000] {logging_mixin.py:117} INFO - [2023-12-23T01:29:09.766+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 9, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-23T01:29:09.802+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:29:10.132+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 0.562 seconds
[2023-12-23T01:29:40.454+0000] {processor.py:156} INFO - Started process (PID=1255) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:29:40.464+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-23T01:29:40.466+0000] {logging_mixin.py:117} INFO - [2023-12-23T01:29:40.465+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:29:40.480+0000] {logging_mixin.py:117} INFO - [2023-12-23T01:29:40.478+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 9, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-23T01:29:40.482+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:29:40.585+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 0.161 seconds
[2023-12-23T01:30:11.376+0000] {processor.py:156} INFO - Started process (PID=1302) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:30:11.408+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-23T01:30:11.409+0000] {logging_mixin.py:117} INFO - [2023-12-23T01:30:11.409+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:30:11.470+0000] {logging_mixin.py:117} INFO - [2023-12-23T01:30:11.447+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 9, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-23T01:30:11.471+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:30:11.649+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 0.290 seconds
[2023-12-23T01:30:42.420+0000] {processor.py:156} INFO - Started process (PID=1357) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:30:42.421+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-23T01:30:42.422+0000] {logging_mixin.py:117} INFO - [2023-12-23T01:30:42.422+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:30:42.436+0000] {logging_mixin.py:117} INFO - [2023-12-23T01:30:42.434+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 9, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-23T01:30:42.437+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:30:42.485+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 0.071 seconds
[2023-12-23T01:31:13.276+0000] {processor.py:156} INFO - Started process (PID=1412) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:31:13.316+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-23T01:31:13.318+0000] {logging_mixin.py:117} INFO - [2023-12-23T01:31:13.318+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:31:13.348+0000] {logging_mixin.py:117} INFO - [2023-12-23T01:31:13.347+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 9, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-23T01:31:13.349+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:31:13.506+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 0.237 seconds
[2023-12-23T01:31:43.701+0000] {processor.py:156} INFO - Started process (PID=1468) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:31:43.760+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-23T01:31:43.762+0000] {logging_mixin.py:117} INFO - [2023-12-23T01:31:43.761+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:31:43.774+0000] {logging_mixin.py:117} INFO - [2023-12-23T01:31:43.772+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 9, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-23T01:31:43.776+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:31:43.877+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 0.184 seconds
[2023-12-23T01:32:25.280+0000] {processor.py:156} INFO - Started process (PID=1519) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:32:25.335+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-23T01:32:25.337+0000] {logging_mixin.py:117} INFO - [2023-12-23T01:32:25.336+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:32:25.358+0000] {logging_mixin.py:117} INFO - [2023-12-23T01:32:25.355+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 9, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-23T01:32:25.359+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:32:25.413+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 0.151 seconds
[2023-12-23T01:32:56.692+0000] {processor.py:156} INFO - Started process (PID=1565) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:32:56.698+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-23T01:32:56.700+0000] {logging_mixin.py:117} INFO - [2023-12-23T01:32:56.699+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:32:56.821+0000] {logging_mixin.py:117} INFO - [2023-12-23T01:32:56.809+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 9, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-23T01:32:56.822+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:32:56.949+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 0.341 seconds
[2023-12-23T01:33:31.588+0000] {processor.py:156} INFO - Started process (PID=1612) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:33:31.635+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-23T01:33:31.640+0000] {logging_mixin.py:117} INFO - [2023-12-23T01:33:31.640+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:33:31.756+0000] {logging_mixin.py:117} INFO - [2023-12-23T01:33:31.730+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 9, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-23T01:33:31.758+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:33:32.131+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 0.593 seconds
[2023-12-23T01:34:16.049+0000] {processor.py:156} INFO - Started process (PID=1657) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:34:16.054+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-23T01:34:16.055+0000] {logging_mixin.py:117} INFO - [2023-12-23T01:34:16.055+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:34:16.110+0000] {logging_mixin.py:117} INFO - [2023-12-23T01:34:16.105+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 9, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-23T01:34:16.111+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:34:16.258+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 0.236 seconds
[2023-12-23T01:34:47.116+0000] {processor.py:156} INFO - Started process (PID=1710) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:34:47.152+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-23T01:34:47.155+0000] {logging_mixin.py:117} INFO - [2023-12-23T01:34:47.154+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:34:47.183+0000] {logging_mixin.py:117} INFO - [2023-12-23T01:34:47.179+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 9, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-23T01:34:47.184+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:34:47.299+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 0.248 seconds
[2023-12-23T01:35:17.779+0000] {processor.py:156} INFO - Started process (PID=1765) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:35:17.780+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-23T01:35:17.782+0000] {logging_mixin.py:117} INFO - [2023-12-23T01:35:17.782+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:35:17.797+0000] {logging_mixin.py:117} INFO - [2023-12-23T01:35:17.795+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 9, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-23T01:35:17.798+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:35:17.945+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 0.173 seconds
[2023-12-23T01:35:48.332+0000] {processor.py:156} INFO - Started process (PID=1810) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:35:48.368+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-23T01:35:48.370+0000] {logging_mixin.py:117} INFO - [2023-12-23T01:35:48.369+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:35:48.421+0000] {logging_mixin.py:117} INFO - [2023-12-23T01:35:48.407+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 9, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-23T01:35:48.422+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:35:48.561+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 0.260 seconds
[2023-12-23T01:36:26.466+0000] {processor.py:156} INFO - Started process (PID=1861) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:36:26.473+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-23T01:36:26.482+0000] {logging_mixin.py:117} INFO - [2023-12-23T01:36:26.481+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:36:26.535+0000] {logging_mixin.py:117} INFO - [2023-12-23T01:36:26.533+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 9, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-23T01:36:26.536+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:36:26.746+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 0.288 seconds
[2023-12-23T01:36:58.160+0000] {processor.py:156} INFO - Started process (PID=1908) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:36:58.245+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-23T01:36:58.261+0000] {logging_mixin.py:117} INFO - [2023-12-23T01:36:58.261+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:36:58.533+0000] {logging_mixin.py:117} INFO - [2023-12-23T01:36:58.505+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 9, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-23T01:36:58.534+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:36:59.111+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 1.130 seconds
[2023-12-23T01:38:06.636+0000] {processor.py:156} INFO - Started process (PID=1967) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:38:06.669+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-23T01:38:06.688+0000] {logging_mixin.py:117} INFO - [2023-12-23T01:38:06.685+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:38:06.863+0000] {logging_mixin.py:117} INFO - [2023-12-23T01:38:06.845+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 9, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-23T01:38:06.871+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:38:07.187+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 0.581 seconds
[2023-12-23T01:39:22.492+0000] {processor.py:156} INFO - Started process (PID=2013) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:39:22.579+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-23T01:39:22.585+0000] {logging_mixin.py:117} INFO - [2023-12-23T01:39:22.582+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:39:23.363+0000] {logging_mixin.py:117} INFO - [2023-12-23T01:39:23.291+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 9, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-23T01:39:23.364+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:39:25.083+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 2.752 seconds
[2023-12-23T01:41:15.855+0000] {processor.py:156} INFO - Started process (PID=2088) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:41:15.909+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-23T01:41:15.959+0000] {logging_mixin.py:117} INFO - [2023-12-23T01:41:15.958+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:41:16.447+0000] {logging_mixin.py:117} INFO - [2023-12-23T01:41:16.420+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 9, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-23T01:41:16.495+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:41:17.916+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 2.150 seconds
[2023-12-23T01:43:50.748+0000] {processor.py:156} INFO - Started process (PID=2165) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:43:50.853+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-23T01:43:50.863+0000] {logging_mixin.py:117} INFO - [2023-12-23T01:43:50.863+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:43:51.125+0000] {logging_mixin.py:117} INFO - [2023-12-23T01:43:51.114+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 9, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-23T01:43:51.126+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:43:51.222+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 0.618 seconds
[2023-12-23T01:44:21.809+0000] {processor.py:156} INFO - Started process (PID=2212) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:44:21.812+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-23T01:44:21.813+0000] {logging_mixin.py:117} INFO - [2023-12-23T01:44:21.813+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:44:21.849+0000] {logging_mixin.py:117} INFO - [2023-12-23T01:44:21.843+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 9, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-23T01:44:21.855+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:44:21.913+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 0.111 seconds
[2023-12-23T01:44:52.579+0000] {processor.py:156} INFO - Started process (PID=2266) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:44:52.616+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-23T01:44:52.617+0000] {logging_mixin.py:117} INFO - [2023-12-23T01:44:52.617+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:44:52.630+0000] {logging_mixin.py:117} INFO - [2023-12-23T01:44:52.628+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 9, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-23T01:44:52.631+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:44:52.779+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 0.229 seconds
[2023-12-23T01:45:22.906+0000] {processor.py:156} INFO - Started process (PID=2319) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:45:22.913+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-23T01:45:22.927+0000] {logging_mixin.py:117} INFO - [2023-12-23T01:45:22.921+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:45:22.979+0000] {logging_mixin.py:117} INFO - [2023-12-23T01:45:22.968+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 9, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-23T01:45:22.981+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:45:23.065+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 0.183 seconds
[2023-12-23T01:45:54.293+0000] {processor.py:156} INFO - Started process (PID=2366) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:45:54.297+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-23T01:45:54.306+0000] {logging_mixin.py:117} INFO - [2023-12-23T01:45:54.306+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:45:54.359+0000] {logging_mixin.py:117} INFO - [2023-12-23T01:45:54.347+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 9, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-23T01:45:54.360+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:45:54.515+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 0.263 seconds
[2023-12-23T01:46:25.027+0000] {processor.py:156} INFO - Started process (PID=2412) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:46:25.033+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-23T01:46:25.036+0000] {logging_mixin.py:117} INFO - [2023-12-23T01:46:25.035+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:46:25.099+0000] {logging_mixin.py:117} INFO - [2023-12-23T01:46:25.096+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 9, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-23T01:46:25.101+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:46:25.189+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 0.187 seconds
[2023-12-23T01:47:00.323+0000] {processor.py:156} INFO - Started process (PID=2465) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:47:00.336+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-23T01:47:00.342+0000] {logging_mixin.py:117} INFO - [2023-12-23T01:47:00.342+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:47:00.510+0000] {logging_mixin.py:117} INFO - [2023-12-23T01:47:00.467+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 9, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-23T01:47:00.511+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:47:00.715+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 0.415 seconds
[2023-12-23T01:47:31.702+0000] {processor.py:156} INFO - Started process (PID=2515) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:47:31.736+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-23T01:47:31.738+0000] {logging_mixin.py:117} INFO - [2023-12-23T01:47:31.738+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:47:31.769+0000] {logging_mixin.py:117} INFO - [2023-12-23T01:47:31.767+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 9, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-23T01:47:31.770+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:47:31.894+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 0.204 seconds
[2023-12-23T01:48:03.501+0000] {processor.py:156} INFO - Started process (PID=2562) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:48:03.539+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-23T01:48:03.541+0000] {logging_mixin.py:117} INFO - [2023-12-23T01:48:03.541+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:48:03.557+0000] {logging_mixin.py:117} INFO - [2023-12-23T01:48:03.555+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 9, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-23T01:48:03.559+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:48:03.867+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 0.389 seconds
[2023-12-23T01:48:35.013+0000] {processor.py:156} INFO - Started process (PID=2615) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:48:35.025+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-23T01:48:35.027+0000] {logging_mixin.py:117} INFO - [2023-12-23T01:48:35.026+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:48:35.071+0000] {logging_mixin.py:117} INFO - [2023-12-23T01:48:35.066+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 9, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-23T01:48:35.072+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:48:35.216+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 0.209 seconds
[2023-12-23T01:49:13.361+0000] {processor.py:156} INFO - Started process (PID=2652) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:49:13.457+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-23T01:49:13.534+0000] {logging_mixin.py:117} INFO - [2023-12-23T01:49:13.487+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:49:14.607+0000] {logging_mixin.py:117} INFO - [2023-12-23T01:49:14.496+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 9, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-23T01:49:14.654+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:49:15.698+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 2.462 seconds
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         [2023-12-23T01:54:30.664+0000] {processor.py:156} INFO - Started process (PID=86) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:54:30.672+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-23T01:54:30.719+0000] {logging_mixin.py:117} INFO - [2023-12-23T01:54:30.685+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:54:31.066+0000] {logging_mixin.py:117} INFO - [2023-12-23T01:54:31.056+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 9, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-23T01:54:31.067+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-23T01:54:31.704+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 1.186 seconds
[2023-12-23T12:05:19.798+0000] {processor.py:156} INFO - Started process (PID=82) to work on /opt/airflow/dags/my_dag_project.py
[2023-12-23T12:05:19.824+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/my_dag_project.py for tasks to queue
[2023-12-23T12:05:19.861+0000] {logging_mixin.py:117} INFO - [2023-12-23T12:05:19.852+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag_project.py
[2023-12-23T12:05:20.491+0000] {logging_mixin.py:117} INFO - [2023-12-23T12:05:20.459+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/my_dag_project.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag_project.py", line 9, in <module>
    from scripts.elt_functions import extract_data, load_vehicle_data, load_trajectory_data
ModuleNotFoundError: No module named 'scripts'
[2023-12-23T12:05:20.492+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag_project.py
[2023-12-23T12:05:23.426+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/my_dag_project.py took 3.684 seconds
